spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: catalogoDB
      port: 27017



 #|    config:
  #    import: "optional:configserver:http://localhost:8888/"


server:
  port: ${PORT:${SERVER_PORT:0}}
  idRandom: ${random.value}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  circuitbreaker:
    instances:
      OnLine:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        slidingWindowSize: 8
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 1
  retry:
    instances:
      OnLine:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - feign.FeignException$InternalServerError


